-- AlterTable
ALTER TABLE "users" ALTER COLUMN "exp" SET DEFAULT 0,
ALTER COLUMN "exp" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "expMonthCount" SET DEFAULT 0,
ALTER COLUMN "expMonthCount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "curLevelExp" SET DEFAULT 0,
ALTER COLUMN "curLevelExp" SET DATA TYPE DOUBLE PRECISION;
